# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
link_with 'OCTabExample', 'OCTabExample Tests'

target 'OCTabExample' do
  pod 'youtube-ios-player-helper', '~> 0.1.4'
end

target 'OCTabExampleTests' do

end

